-----------------------------------New Session-----------------------------------
2021-04-26 16:25:48,472 | INFO | discord.client | logging in using static token
2021-04-26 16:25:49,763 | INFO | discord.gateway | Shard ID None has sent the IDENTIFY payload.
2021-04-26 16:25:50,043 | INFO | discord.gateway | Shard ID None has connected to Gateway: ["gateway-prd-main-qmnl",{"micros":90753,"calls":["discord-sessions-prd-2-63",{"micros":86720,"calls":["start_session",{"micros":30263,"calls":["api-prd-main-71hm",{"micros":27395,"calls":["get_user",{"micros":2267},"add_authorized_ip",{"micros":1742},"get_guilds",{"micros":5604},"coros_wait",{"micros":2}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":26173,"calls":[]}]}]}] (Session ID: 8bc88c21c2561b04c6b3081bc7885926).
2021-04-26 16:25:52,059 | INFO | discord | Bot ready to use!
2021-04-26 16:26:51,612 | ERROR | discord | Command not found from: <@532157271531061255>
2021-04-26 16:27:03,246 | ERROR | discord | Bad argument error from: <@532157271531061255>
2021-04-26 16:28:17,628 | INFO | discord | Created new meeting users: ['Vexumi ', 'Bot Yandex.Taxi ']; from: <@532157271531061255>; time: 10 sec
2021-04-26 16:28:29,096 | INFO | discord | Meeting end!
2021-04-26 16:29:30,255 | INFO | discord | Starting spam to id:<@!780798543622569984>, from: <@532157271531061255>
2021-04-26 16:29:35,069 | INFO | discord | Spam to id: <@!780798543622569984>
2021-04-26 16:29:40,420 | INFO | discord | Spam to id: <@!780798543622569984>
2021-04-26 16:29:45,691 | INFO | discord | Spam to id: <@!780798543622569984>
2021-04-26 16:29:50,384 | INFO | discord | Spammer stopped by: <@532157271531061255>
2021-04-26 16:30:23,827 | INFO | discord.voice_client | Connecting to voice...
2021-04-26 16:30:23,828 | INFO | discord.voice_client | Starting voice handshake...
2021-04-26 16:30:24,154 | INFO | discord.voice_client | Voice handshake complete. Endpoint found russia7540.discord.media (IP: None)
2021-04-26 16:30:25,022 | INFO | discord.gateway | selected the voice protocol for use (xsalsa20_poly1305_lite)
2021-04-26 16:30:25,151 | INFO | discord.gateway | received secret key for voice connection
2021-04-26 16:30:27,432 | INFO | discord.player | Preparing to terminate ffmpeg process 20332.
2021-04-26 16:30:27,433 | INFO | discord.player | ffmpeg process 20332 successfully terminated with return code of 0.
2021-04-26 16:30:27,777 | INFO | discord.voice_client | The voice handshake is being terminated for Channel ID 832913863930150917 (Guild ID 832913863930150912)
2021-04-26 16:30:27,778 | INFO | discord.voice_client | The voice client has been removed for Channel ID 832913863930150917 (Guild ID 832913863930150912)
2021-04-26 16:30:27,778 | INFO | discord | <@532157271531061255> killed Bot Yandex.Taxi
2021-04-26 16:30:27,778 | INFO | discord.voice_client | Disconnecting from voice normally, close code 1000.
2021-04-26 16:30:44,789 | INFO | discord | Get mem from: 532157271531061255
2021-04-26 16:31:12,988 | INFO | discord | Russian roulette started time:10 min, from: <@532157271531061255>
2021-04-26 16:34:26,300 | INFO | discord | <@532157271531061255> kicked Bot Yandex.Taxi, reason: Couldn't survive on the server
2021-04-26 16:34:52,022 | INFO | discord | Wikipedia page founded, url: https://ru.wikipedia.org/wiki/Python, from: 532157271531061255
2021-04-26 16:36:21,460 | ERROR | discord | Bad argument error from: <@532157271531061255>
2021-04-26 16:37:07,100 | WARNING | discord | Bug reported by: <@532157271531061255>
2021-04-26 16:39:37,250 | INFO | discord.voice_client | Connecting to voice...
2021-04-26 16:39:37,250 | INFO | discord.voice_client | Starting voice handshake...
2021-04-26 16:39:37,576 | INFO | discord.voice_client | Voice handshake complete. Endpoint found russia9262.discord.media (IP: None)
2021-04-26 16:39:38,436 | INFO | discord.gateway | selected the voice protocol for use (xsalsa20_poly1305_lite)
2021-04-26 16:39:38,566 | INFO | discord.gateway | received secret key for voice connection
2021-04-26 16:39:44,033 | INFO | discord | Music started by: <@532157271531061255>, music: https://www.youtube.com/watch?v=RLWcYADoV84
2021-04-26 16:40:04,429 | INFO | discord.voice_client | The voice handshake is being terminated for Channel ID 832913863930150917 (Guild ID 832913863930150912)
2021-04-26 16:40:04,430 | INFO | discord.voice_client | The voice client has been removed for Channel ID 832913863930150917 (Guild ID 832913863930150912)
2021-04-26 16:40:04,430 | INFO | discord | Music stopped by: <@532157271531061255>
2021-04-26 16:40:04,430 | INFO | discord.voice_client | Disconnecting from voice normally, close code 1000.
2021-04-26 16:40:04,435 | INFO | discord.player | Preparing to terminate ffmpeg process 3084.
2021-04-26 16:40:04,435 | INFO | discord.player | ffmpeg process 3084 has not terminated. Waiting to terminate...
2021-04-26 16:40:04,455 | INFO | discord.player | ffmpeg process 3084 should have terminated with a return code of 1.
2021-04-26 16:40:13,370 | INFO | discord.voice_client | Connecting to voice...
2021-04-26 16:40:13,371 | INFO | discord.voice_client | Starting voice handshake...
2021-04-26 16:40:13,706 | INFO | discord.voice_client | Voice handshake complete. Endpoint found russia9262.discord.media (IP: None)
2021-04-26 16:40:14,500 | INFO | discord.gateway | selected the voice protocol for use (xsalsa20_poly1305_lite)
2021-04-26 16:40:14,630 | INFO | discord.gateway | received secret key for voice connection
2021-04-26 16:40:16,955 | INFO | discord.voice_client | The voice handshake is being terminated for Channel ID 832913863930150917 (Guild ID 832913863930150912)
2021-04-26 16:40:16,955 | INFO | discord.voice_client | The voice client has been removed for Channel ID 832913863930150917 (Guild ID 832913863930150912)
2021-04-26 16:40:16,956 | INFO | discord | <@532157271531061255> killed Vexumi
2021-04-26 16:40:16,957 | INFO | discord.voice_client | Disconnecting from voice normally, close code 1000.
2021-04-26 16:40:16,963 | INFO | discord.player | Preparing to terminate ffmpeg process 5224.
2021-04-26 16:40:16,963 | INFO | discord.player | ffmpeg process 5224 has not terminated. Waiting to terminate...
2021-04-26 16:40:16,984 | INFO | discord.player | ffmpeg process 5224 should have terminated with a return code of 1.
2021-04-26 16:41:12,427 | INFO | discord.voice_client | Connecting to voice...
2021-04-26 16:41:12,427 | INFO | discord.voice_client | Starting voice handshake...
2021-04-26 16:41:12,753 | INFO | discord.voice_client | Voice handshake complete. Endpoint found russia132.discord.media (IP: None)
2021-04-26 16:41:13,566 | INFO | discord.gateway | selected the voice protocol for use (xsalsa20_poly1305_lite)
2021-04-26 16:41:13,708 | INFO | discord.gateway | received secret key for voice connection
2021-04-26 16:41:22,430 | INFO | discord | Roullet shoot to: Vexumi
2021-04-26 16:41:22,844 | INFO | discord.player | Preparing to terminate ffmpeg process 16168.
2021-04-26 16:41:22,845 | INFO | discord.player | ffmpeg process 16168 successfully terminated with return code of 0.
2021-04-26 16:41:38,280 | INFO | discord.voice_client | The voice handshake is being terminated for Channel ID 832913863930150917 (Guild ID 832913863930150912)
2021-04-26 16:41:38,280 | INFO | discord.voice_client | The voice client has been removed for Channel ID 832913863930150917 (Guild ID 832913863930150912)
2021-04-26 16:41:38,284 | INFO | discord.voice_client | Disconnecting from voice normally, close code 1000.
2021-04-26 16:41:38,727 | INFO | discord | Russian Roulette stopped by: <@532157271531061255>
2021-04-26 16:49:58,550 | INFO | discord.voice_client | Connecting to voice...
2021-04-26 16:49:58,550 | INFO | discord.voice_client | Starting voice handshake...
2021-04-26 16:49:58,912 | INFO | discord.voice_client | Voice handshake complete. Endpoint found russia5010.discord.media (IP: None)
2021-04-26 16:49:59,779 | INFO | discord.gateway | selected the voice protocol for use (xsalsa20_poly1305_lite)
2021-04-26 16:49:59,916 | INFO | discord.gateway | received secret key for voice connection
-----------------------------------New Session-----------------------------------
2021-04-26 17:33:19,624 | INFO | discord.client | logging in using static token
2021-04-26 17:33:20,903 | INFO | discord.gateway | Shard ID None has sent the IDENTIFY payload.
2021-04-26 17:33:21,200 | INFO | discord.gateway | Shard ID None has connected to Gateway: ["gateway-prd-main-05b3",{"micros":97738,"calls":["discord-sessions-prd-2-41",{"micros":95713,"calls":["start_session",{"micros":34757,"calls":["api-prd-main-kn62",{"micros":31914,"calls":["get_user",{"micros":2678},"add_authorized_ip",{"micros":1499},"get_guilds",{"micros":5959},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":47992,"calls":[]}]}]}] (Session ID: 4fca4ed6804ca68619f6b5cfb0dbe3af).
2021-04-26 17:33:23,228 | INFO | discord | Bot ready to use!
2021-04-26 17:33:24,881 | WARNING | discord | Command to test def sended
2021-04-26 17:33:29,381 | INFO | discord.voice_client | Connecting to voice...
2021-04-26 17:33:29,381 | INFO | discord.voice_client | Starting voice handshake...
2021-04-26 17:33:29,730 | INFO | discord.voice_client | Voice handshake complete. Endpoint found russia5010.discord.media (IP: None)
2021-04-26 17:33:30,579 | INFO | discord.gateway | selected the voice protocol for use (xsalsa20_poly1305_lite)
2021-04-26 17:33:30,776 | INFO | discord.gateway | received secret key for voice connection
2021-04-26 17:33:33,638 | INFO | discord | Music started by: <@532157271531061255>, music: https://www.youtube.com/watch?v=RLWcYADoV84
2021-04-26 17:34:33,192 | INFO | discord.voice_client | The voice handshake is being terminated for Channel ID 832913863930150917 (Guild ID 832913863930150912)
2021-04-26 17:34:33,192 | INFO | discord.voice_client | The voice client has been removed for Channel ID 832913863930150917 (Guild ID 832913863930150912)
2021-04-26 17:34:33,192 | INFO | discord | Music stopped by: <@532157271531061255>
2021-04-26 17:34:33,193 | INFO | discord.voice_client | Disconnecting from voice normally, close code 1000.
2021-04-26 17:34:33,198 | INFO | discord.player | Preparing to terminate ffmpeg process 19896.
2021-04-26 17:34:33,198 | INFO | discord.player | ffmpeg process 19896 has not terminated. Waiting to terminate...
2021-04-26 17:34:33,211 | INFO | discord.player | ffmpeg process 19896 should have terminated with a return code of 1.
-----------------------------------New Session-----------------------------------
2021-04-26 17:34:45,765 | INFO | discord.client | logging in using static token
2021-04-26 17:34:46,801 | INFO | discord.gateway | Shard ID None has sent the IDENTIFY payload.
2021-04-26 17:34:47,918 | INFO | discord.gateway | Shard ID None has connected to Gateway: ["gateway-prd-main-06z4",{"micros":923694,"calls":["discord-sessions-prd-2-30",{"micros":921193,"calls":["start_session",{"micros":857466,"calls":["api-prd-main-x5wx",{"micros":846458,"calls":["get_user",{"micros":4800},"add_authorized_ip",{"micros":9978},"get_guilds",{"micros":6778},"coros_wait",{"micros":2}]}]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":39162,"calls":[]}]}]}] (Session ID: 9fb982b922e8afdb356118f741583783).
2021-04-26 17:34:48,838 | INFO | discord.voice_client | Connecting to voice...
2021-04-26 17:34:48,838 | INFO | discord.voice_client | Starting voice handshake...
2021-04-26 17:34:49,181 | INFO | discord.voice_client | Voice handshake complete. Endpoint found russia5010.discord.media (IP: None)
2021-04-26 17:34:49,904 | INFO | discord.gateway | selected the voice protocol for use (xsalsa20_poly1305_lite)
2021-04-26 17:34:49,954 | INFO | discord | Bot ready to use!
2021-04-26 17:34:50,035 | INFO | discord.gateway | received secret key for voice connection
2021-04-26 17:34:53,061 | INFO | discord | Music started by: <@532157271531061255>, music: https://www.youtube.com/watch?v=RLWcYADoV84
2021-04-26 17:35:41,362 | INFO | discord.player | Preparing to terminate ffmpeg process 2744.
2021-04-26 17:35:41,364 | INFO | discord.player | ffmpeg process 2744 has not terminated. Waiting to terminate...
2021-04-26 17:35:41,366 | INFO | discord.voice_client | The voice handshake is being terminated for Channel ID 832913863930150917 (Guild ID 832913863930150912)
2021-04-26 17:35:41,366 | INFO | discord.voice_client | The voice client has been removed for Channel ID 832913863930150917 (Guild ID 832913863930150912)
2021-04-26 17:35:41,366 | INFO | discord | Music stopped by: <@532157271531061255>
2021-04-26 17:35:41,367 | INFO | discord.voice_client | Disconnecting from voice normally, close code 1000.
2021-04-26 17:35:41,373 | INFO | discord.player | ffmpeg process 2744 should have terminated with a return code of 1.
-----------------------------------New Session-----------------------------------
2021-04-26 17:39:18,011 | INFO | discord.client | logging in using static token
2021-04-26 17:39:19,129 | INFO | discord.gateway | Shard ID None has sent the IDENTIFY payload.
2021-04-26 17:39:19,472 | INFO | discord.gateway | Shard ID None has connected to Gateway: ["gateway-prd-main-6hzd",{"micros":104944,"calls":["discord-sessions-prd-2-84",{"micros":104223,"calls":["start_session",{"micros":51977,"calls":["api-prd-main-3ngx",{"micros":48937,"calls":["get_user",{"micros":5387},"add_authorized_ip",{"micros":3416},"get_guilds",{"micros":9327},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":22083,"calls":[]}]}]}] (Session ID: 55e4c109c0c665afdf8e4bcc2494c147).
2021-04-26 17:39:21,489 | INFO | discord | Bot ready to use!
2021-04-26 17:43:18,057 | INFO | discord.voice_client | Connecting to voice...
2021-04-26 17:43:18,057 | INFO | discord.voice_client | Starting voice handshake...
2021-04-26 17:43:18,509 | INFO | discord.voice_client | Voice handshake complete. Endpoint found russia5010.discord.media (IP: None)
2021-04-26 17:43:19,362 | INFO | discord.gateway | selected the voice protocol for use (xsalsa20_poly1305_lite)
2021-04-26 17:43:19,521 | INFO | discord.gateway | received secret key for voice connection
2021-04-26 17:43:22,339 | INFO | discord | Music started by: <@532157271531061255>, music: https://www.youtube.com/watch?v=RLWcYADoV84
2021-04-26 17:44:02,151 | INFO | discord.voice_client | The voice handshake is being terminated for Channel ID 832913863930150917 (Guild ID 832913863930150912)
2021-04-26 17:44:02,152 | INFO | discord.voice_client | The voice client has been removed for Channel ID 832913863930150917 (Guild ID 832913863930150912)
2021-04-26 17:44:02,152 | INFO | discord | Music stopped by: <@532157271531061255>
2021-04-26 17:44:02,152 | INFO | discord.voice_client | Disconnecting from voice normally, close code 1000.
2021-04-26 17:44:02,160 | INFO | discord.player | Preparing to terminate ffmpeg process 17004.
2021-04-26 17:44:02,161 | INFO | discord.player | ffmpeg process 17004 has not terminated. Waiting to terminate...
2021-04-26 17:44:02,184 | INFO | discord.player | ffmpeg process 17004 should have terminated with a return code of 1.
2021-04-26 17:57:21,910 | INFO | discord.voice_client | Connecting to voice...
2021-04-26 17:57:21,910 | INFO | discord.voice_client | Starting voice handshake...
2021-04-26 17:57:22,246 | INFO | discord.voice_client | Voice handshake complete. Endpoint found russia8816.discord.media (IP: None)
2021-04-26 17:57:23,068 | INFO | discord.gateway | selected the voice protocol for use (xsalsa20_poly1305_lite)
2021-04-26 17:57:23,192 | INFO | discord.gateway | received secret key for voice connection
2021-04-26 17:57:23,196 | INFO | discord | Joined to voice channel. Command from: <@532157271531061255>
2021-04-26 17:57:44,880 | INFO | discord.voice_client | The voice handshake is being terminated for Channel ID 832913863930150917 (Guild ID 832913863930150912)
2021-04-26 17:57:44,880 | INFO | discord.voice_client | The voice client has been removed for Channel ID 832913863930150917 (Guild ID 832913863930150912)
2021-04-26 17:57:44,880 | INFO | discord | Bot disconnected by: <@532157271531061255>
2021-04-26 17:57:44,880 | INFO | discord.voice_client | Disconnecting from voice normally, close code 1000.
2021-04-26 17:58:04,225 | INFO | discord.gateway | Websocket closed with 1006, attempting a reconnect.
2021-04-26 17:58:04,229 | INFO | discord.client | Got a request to RESUME the websocket.
2021-04-26 17:58:04,433 | ERROR | discord.client | Attempting a reconnect in 1.63s
Traceback (most recent call last):
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 964, in _create_direct_connection
    hosts = await asyncio.shield(self._resolve_host(
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 829, in _resolve_host
    addrs = await \
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\resolver.py", line 29, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\glebg\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\glebg\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\glebg\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\discord\client.py", line 521, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\glebg\AppData\Local\Programs\Python\Python38-32\lib\asyncio\tasks.py", line 483, in wait_for
    return fut.result()
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\discord\gateway.py", line 254, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\discord\http.py", line 907, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\discord\http.py", line 185, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py", line 480, in _request
    conn = await self._connector.connect(
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 971, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
2021-04-26 19:47:38,001 | ERROR | discord.client | Attempting a reconnect in 1.59s
Traceback (most recent call last):
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 964, in _create_direct_connection
    hosts = await asyncio.shield(self._resolve_host(
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 829, in _resolve_host
    addrs = await \
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\resolver.py", line 29, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\glebg\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\glebg\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\glebg\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\discord\client.py", line 521, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\glebg\AppData\Local\Programs\Python\Python38-32\lib\asyncio\tasks.py", line 483, in wait_for
    return fut.result()
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\discord\gateway.py", line 254, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\discord\http.py", line 907, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\discord\http.py", line 185, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py", line 480, in _request
    conn = await self._connector.connect(
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 971, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
2021-04-26 19:47:41,489 | ERROR | discord.client | Attempting a reconnect in 3.07s
Traceback (most recent call last):
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 964, in _create_direct_connection
    hosts = await asyncio.shield(self._resolve_host(
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 829, in _resolve_host
    addrs = await \
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\resolver.py", line 29, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\glebg\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\glebg\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\glebg\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\discord\client.py", line 521, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\glebg\AppData\Local\Programs\Python\Python38-32\lib\asyncio\tasks.py", line 483, in wait_for
    return fut.result()
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\discord\gateway.py", line 254, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\discord\http.py", line 907, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\discord\http.py", line 185, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py", line 480, in _request
    conn = await self._connector.connect(
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 971, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
2021-04-26 19:47:44,569 | ERROR | discord.client | Attempting a reconnect in 4.20s
Traceback (most recent call last):
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 964, in _create_direct_connection
    hosts = await asyncio.shield(self._resolve_host(
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 829, in _resolve_host
    addrs = await \
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\resolver.py", line 29, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\glebg\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\glebg\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\glebg\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\discord\client.py", line 521, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\glebg\AppData\Local\Programs\Python\Python38-32\lib\asyncio\tasks.py", line 483, in wait_for
    return fut.result()
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\discord\gateway.py", line 254, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\discord\http.py", line 907, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\discord\http.py", line 185, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py", line 480, in _request
    conn = await self._connector.connect(
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 971, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
2021-04-26 19:47:48,777 | ERROR | discord.client | Attempting a reconnect in 8.71s
Traceback (most recent call last):
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 964, in _create_direct_connection
    hosts = await asyncio.shield(self._resolve_host(
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 829, in _resolve_host
    addrs = await \
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\resolver.py", line 29, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\glebg\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\glebg\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\glebg\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\discord\client.py", line 521, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\glebg\AppData\Local\Programs\Python\Python38-32\lib\asyncio\tasks.py", line 483, in wait_for
    return fut.result()
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\discord\gateway.py", line 254, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\discord\http.py", line 907, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\discord\http.py", line 185, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py", line 480, in _request
    conn = await self._connector.connect(
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "C:\Users\glebg\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 971, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
2021-04-26 19:47:58,217 | INFO | discord.gateway | Shard ID None has sent the RESUME payload.
2021-04-26 19:47:58,420 | INFO | discord.gateway | Shard ID None session has been invalidated.
2021-04-26 19:47:58,686 | INFO | discord.client | Got a request to IDENTIFY the websocket.
2021-04-26 19:48:04,149 | INFO | discord.gateway | Shard ID None has sent the IDENTIFY payload.
2021-04-26 19:48:04,417 | INFO | discord.gateway | Shard ID None has connected to Gateway: ["gateway-prd-main-6v94",{"micros":63188,"calls":["discord-sessions-prd-2-113",{"micros":57862,"calls":["start_session",{"micros":32800,"calls":["api-prd-main-6jvp",{"micros":29815,"calls":["get_user",{"micros":2691},"add_authorized_ip",{"micros":1493},"get_guilds",{"micros":4827},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: 6c205580d04d4a057bfb18ce18312f07).
2021-04-26 19:48:06,466 | INFO | discord | Bot ready to use!
-----------------------------------New Session-----------------------------------
2021-04-26 19:51:46,465 | INFO | discord.client | logging in using static token
2021-04-26 19:51:47,284 | INFO | discord.gateway | Shard ID None has sent the IDENTIFY payload.
2021-04-26 19:51:47,538 | INFO | discord.gateway | Shard ID None has connected to Gateway: ["gateway-prd-main-jmpv",{"micros":52417,"calls":["discord-sessions-prd-2-12",{"micros":47984,"calls":["start_session",{"micros":43967,"calls":["api-prd-main-l4wk",{"micros":40535,"calls":["get_user",{"micros":2835},"add_authorized_ip",{"micros":3581},"get_guilds",{"micros":5194},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":113,"calls":[]}]}]}] (Session ID: 7c3ee9eea9c42b3b25c7671c9f662c6a).
2021-04-26 19:51:49,555 | INFO | discord | Bot ready to use!
2021-04-26 19:51:54,463 | INFO | discord.voice_client | Connecting to voice...
2021-04-26 19:51:54,463 | INFO | discord.voice_client | Starting voice handshake...
2021-04-26 19:51:54,816 | INFO | discord.voice_client | Voice handshake complete. Endpoint found russia2487.discord.media (IP: None)
2021-04-26 19:51:55,251 | INFO | discord.gateway | selected the voice protocol for use (xsalsa20_poly1305_lite)
2021-04-26 19:51:55,311 | INFO | discord.gateway | received secret key for voice connection
2021-04-26 19:51:57,108 | INFO | discord | Music started by: <@532157271531061255>, music: https://www.youtube.com/watch?v=RLWcYADoV84
2021-04-26 19:51:59,894 | INFO | discord.voice_client | The voice handshake is being terminated for Channel ID 814716051652345928 (Guild ID 731080187596374087)
2021-04-26 19:51:59,894 | INFO | discord.voice_client | The voice client has been removed for Channel ID 814716051652345928 (Guild ID 731080187596374087)
2021-04-26 19:51:59,894 | INFO | discord | Music stopped by: <@532157271531061255>
2021-04-26 19:51:59,894 | INFO | discord.voice_client | Disconnecting from voice normally, close code 1000.
2021-04-26 19:51:59,909 | INFO | discord.player | Preparing to terminate ffmpeg process 11704.
2021-04-26 19:51:59,909 | INFO | discord.player | ffmpeg process 11704 has not terminated. Waiting to terminate...
2021-04-26 19:51:59,924 | INFO | discord.player | ffmpeg process 11704 should have terminated with a return code of 1.
2021-04-26 19:52:03,895 | INFO | discord.voice_client | Connecting to voice...
2021-04-26 19:52:03,895 | INFO | discord.voice_client | Starting voice handshake...
2021-04-26 19:52:04,249 | INFO | discord.voice_client | Voice handshake complete. Endpoint found russia2487.discord.media (IP: None)
2021-04-26 19:52:04,576 | INFO | discord.gateway | selected the voice protocol for use (xsalsa20_poly1305_lite)
2021-04-26 19:52:04,625 | INFO | discord.gateway | received secret key for voice connection
2021-04-26 19:52:06,480 | INFO | discord.player | Preparing to terminate ffmpeg process 7744.
2021-04-26 19:52:06,481 | INFO | discord.player | ffmpeg process 7744 successfully terminated with return code of 0.
2021-04-26 19:52:06,498 | INFO | discord.voice_client | The voice handshake is being terminated for Channel ID 814716051652345928 (Guild ID 731080187596374087)
2021-04-26 19:52:06,498 | INFO | discord.voice_client | The voice client has been removed for Channel ID 814716051652345928 (Guild ID 731080187596374087)
2021-04-26 19:52:06,498 | INFO | discord | <@532157271531061255> killed A
2021-04-26 19:52:06,498 | INFO | discord.voice_client | Disconnecting from voice normally, close code 1000.
-----------------------------------New Session-----------------------------------
2021-04-26 19:53:25,517 | INFO | discord.client | logging in using static token
2021-04-26 19:53:26,480 | INFO | discord.gateway | Shard ID None has sent the IDENTIFY payload.
2021-04-26 19:53:26,756 | INFO | discord.gateway | Shard ID None has connected to Gateway: ["gateway-prd-main-1jtg",{"micros":70759,"calls":["discord-sessions-prd-2-146",{"micros":69530,"calls":["start_session",{"micros":43338,"calls":["api-prd-main-gv0h",{"micros":40795,"calls":["get_user",{"micros":4568},"add_authorized_ip",{"micros":1798},"get_guilds",{"micros":7096},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":888,"calls":[]}]}]}] (Session ID: c63af73a9e74eadbb2a6455b770e270e).
2021-04-26 19:53:28,769 | INFO | discord | Bot ready to use!
2021-04-26 19:53:36,346 | WARNING | discord | Command to test def sended
2021-04-26 19:53:38,934 | WARNING | discord | Command to test def sended
-----------------------------------New Session-----------------------------------
2021-04-26 19:53:51,879 | INFO | discord.client | logging in using static token
2021-04-26 19:53:52,673 | INFO | discord.gateway | Shard ID None has sent the IDENTIFY payload.
2021-04-26 19:53:52,935 | INFO | discord.gateway | Shard ID None has connected to Gateway: ["gateway-prd-main-7hrs",{"micros":60816,"calls":["discord-sessions-prd-2-122",{"micros":59414,"calls":["start_session",{"micros":33741,"calls":["api-prd-main-z0c6",{"micros":30404,"calls":["get_user",{"micros":2802},"add_authorized_ip",{"micros":2742},"get_guilds",{"micros":7362},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":20903,"calls":[]}]}]}] (Session ID: cdc94eb626bb80213f3a4a561c5db0f4).
2021-04-26 19:53:54,948 | INFO | discord | Bot ready to use!
2021-04-26 19:54:36,519 | WARNING | discord | Command to test def sended
-----------------------------------New Session-----------------------------------
2021-04-26 19:55:55,529 | INFO | discord.client | logging in using static token
2021-04-26 19:55:56,391 | INFO | discord.gateway | Shard ID None has sent the IDENTIFY payload.
2021-04-26 19:55:56,666 | INFO | discord.gateway | Shard ID None has connected to Gateway: ["gateway-prd-main-qmnl",{"micros":66554,"calls":["discord-sessions-prd-2-87",{"micros":65443,"calls":["start_session",{"micros":26841,"calls":["api-prd-main-tzkn",{"micros":23913,"calls":["get_user",{"micros":2863},"add_authorized_ip",{"micros":1383},"get_guilds",{"micros":3545},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":17485,"calls":[]}]}]}] (Session ID: 0fff2874cac36935d7a4858a78684f1f).
2021-04-26 19:55:58,679 | INFO | discord | Bot ready to use!
2021-04-26 19:56:01,086 | WARNING | discord | Command to test def sended
